[book]
authors = ["Oriol Gómez Díaz"]
language = "ca"
multilingual = false
src = "src"
title = "Apunts ASGBD - Administració de Sistemes Gestors de Bases de Dades"

[output.html]
git-repository-url = "https://github.com/oriolgomezdiaz/apunts-asgbd"